zewelor/bt-mqtt-gateway

- config.py
Hi!
A little fix for the [CVE-2017-2809](https://nvd.nist.gov/vuln/detail/CVE-2017-2809).
`yaml.load` is not safe, you can pass executable code to it!
This CVE speak about ansible-vault but the problem is the same with your application.
Example:
```shell
$ echo '!!python/object/apply:os.system ["echo powned; uname -a"]' > config.yaml
$ ./gateway.py
powned
Linux vm 4.8.0-54-generic #57~16.04.1-Ubuntu SMP Wed May 24 16:22:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
...
```
Have a nice day :)
> fix CVE-2017-2809 - code injection interpreted by yaml loader

- mqtt.py
- workers/thermostat.py
- workers_manager.py
I refer to the "topic_prefix" in the mqtt section as "global_topic_prefix" to not get confused with the "topic_prefix" in the worker section. 
After the revert of parts of the previous fix it remains that the subscription is corrected ("global_topic_prefix/topic_prefix/other/stuff/here"). But having a "global_topic_prefix" and a "topic_prefix" leads to an unpack error in thermostat.py (line 74) again. 
As `self.topic_prefix` refers to "topic_prefix" in this example (class ThermostatWorker), we cannot strip "global_topic_prefix" because we have no access to it at this place. This patch adds the "global_topic_prefix" to the mqtt-Clients userdata (mqtt.py) so that it can be accessed in the callback wrapper (workers_manager.py). The callback wrapper is modified to centrally remove the …
> Fix global mqtt_prefix try 2

- workers/mithermometer.py
Explicitly disabling the cache for each attribute leads to unnecessary BTLE queries. A response from the device for sensor-data always contains [both the temperature and humidity](https://github.com/hobbypunk90/mithermometer/blob/ec49fc3a6c67d383433194306a19f1cc03a50a76/mithermometer/mithermometer_poller.py#L173). With `read_cached=False` we force two separate BTLE queries instead of only one.
The proposed changes keeps the disabled cache but only clears it once before polling for attributes. The query for temperature polls the device for sensor data which in turn returns data for temperature and humidity and fills the cache. The subsequent query for humidity uses that cache.
> mithermometer: Use cache for identical BTLE polls

- README.md
- workers_manager.py
This adds the ability to dynamically set the `update_interval` of a device via MQTT.
It is used by publishing a MQTT message containing the new `update_interval` in seconds to the `/update_interval` topic of a device-type.
Usage examples:
```
mosquitto_pub -h localhost -t 'miflora/update_interval' -m '150'
mosquitto_pub -h localhost -t 'mithermometer/update_interval' -m '30'
```
Motivation for this change:
It may be desirable to set a long `update_interval` to conserve battery, but situations can arise which require quicker updates.
An example of this would be using MiFlora devices, you may have them set to update once per 30mins-1hr, however when watering you may want to have their status update every minute.
Or when using BLE tracking, you may want to increase the update interval when …
> Feature: dynamic update intervals

- workers/miflora.py
This is analogue to #38. A cache timeout of `0` leads to unnecessary BTLE queries.
Debug log of miflora per query before this change:
```
Filling cache with new sensor data.
Received result for handle %s: %s 56 5E 15 32 2E 37 2E 30
Received result for handle %s: %s 53 EA 00 00 A3 00 00 00 1A 36 00 02 3C 00 FB 34 9B
Filling cache with new sensor data.
Received result for handle %s: %s 53 EA 00 00 D5 00 00 00 1A 36 00 02 3C 00 FB 34 9B
Filling cache with new sensor data.
Received result for handle %s: %s 53 EA 00 00 02 01 00 00 1A 33 00 02 3C 00 FB 34 9B
Filling cache with new sensor data.
Received result for handle %s: %s 53 EA 00 00 B5 00 00 00 1A 35 00 02 3C 00 FB 34 9B
```
Debug log of miflora per query after this change:
```
Filling cache with new sensor data.
Received result for …
```
> miflora: Use cache for identical BTLE polls

- config.yaml.example
- utils.py
- workers/blescanmulti.py
Scanning ble tags for presence is looking like a good idea, but it can be a lot of problematic. At least 5 times during day beacon was not found by scanning, this result in instant mark person as not at home. Also by default it was using active way of scanning devices that force devices to resend discover info and if you do it too often it will drain battery very fast. Also this module is spamming MQTT by updating status each scan interval. I have rewrite this module and added extra options that allow you personalise everything. Starting from time of scan, mode of scanning and after what time of missing device we should send MQTT message with update
> blescanmulti - improve scanners options

- gateway.py
- logger.py
- logger.yaml
- mqtt.py
- workers/base.py
- workers/blescanmulti.py
- workers/linakdesk.py
- workers/miflora.py
- workers/miscale.py
- workers/mithermometer.py
- workers/mysensors.py
- workers/thermostat.py
- workers/toothbrush.py
- workers_manager.py
This is basically a rework of the whole logging mechanism. It is meant to provide users adequate feedback for normal operation, but also gives extended information when running in debug mode. Some facts:
* Logging configuration in `logger.yaml`
* Shows stack-traces only in debug mode (Only applies to non fatal errors like timeouts or disconnects)
* Prevents pip from destroying the python ROOT logging configuration (was seen as duplicate stack-traces for example)
* So far I only improved the output for thermostat, miflora and mithermometer devices, as these are the ones I have.
Without `-q` or `-d` the output looks like this:
```
19:27:36 Adding 5 thermostat devices
19:27:39 Adding 1 mithermometer devices
19:27:39 Updating 5 thermostat devices
19:27:55 Updating 1 mithermometer devices …
```
> Improved logging mechanism (and a few minor goodies)

- workers/miflora.py
- workers/mithermometer.py
This updates miflora and mithermometer such that btlewrap 0.0.4 is included which fixes #39.
miflora got a proper release: open-homeautomation/miflora#117, so we can include that cleanly. mithermomether however not yet: hobbypunk90/mithermometer#2. Until this got merged, I include the source of that PR directly.
Is that temporary solution ok, @zewelor?
> Update dependencies to include btlewrap 0.0.4

- config.yaml.example
- gateway.py
- workers/base.py
- workers/blescanmulti.py
- workers/linakdesk.py
- workers/miscale.py
- workers_manager.py
Hey @zewelor 
This allows the timeout for commands to be configured through the `config.yaml` file. One can either configure this globally for all workers or individual per worker. Both is optional though, the default of 35 seconds is kept either way. Thus this change is fully backwards compatible to existing configurations.
> Configurable command timeout

- config.yaml.example
- workers/toothbrush_homeassistant.py
Based on toothbrush worker but this worker is built specially for Home Assistant.
Differences are:
- It doesn't use separate topics for each attribute
- Home Assistant autoconf is published once per device
- Availability topic is only used for updating online/offline in Home Assistant. When online it will start publishing the state and attributes to 2 separate topics.
- Different config params
- The worker has dicts with possible brush states, modes and sectors
- It sends a one time retained Home Assistant autoconfig message to automatically setup a sensor with the correct topics
- It sends the state in a state topic and other attributes in an attribute topic (when state online)
> Added toothbrush worker with Home Assistant support

- workers/ibbq.py
worker for inkbird IBT-2X BBQ thermometer. very likely also supports other thermometers  from inkbird and other that use same hardware. But not tested, as If have only the 2X. 
Using the homeassistant MQTT integration to create charts and alarms  during low+slow BBQing. 
provides temperatures, battery_level and online status. Detects thermometer after it was off, like changing battery. 
You can't monitor the device with blescanmulti in parallel, as it stays connected.
- [x ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x] This change requires a documentation update
sample gateway **config.yaml**
```
ibbq:
args:
devices:
testbbq: f0:45:da:3f:03:1c
topic_prefix: ibbq
update_interval: 30 …
```
> Support for Inkbird BLE BBQ Thermometer

- Dockerfile
- start.sh
i add basically support for docker. 
with `docker build -t test/bt-mqtt-gateway .` you can build the container
and for example with `docker run -d --name bt-mqtt --network=host -v $PWD:/config test/bt-mqtt-gateway` you can run it as detached docker container 🙂
> add docker support

- workers/thermostat.py
adds the payload_on and payload_off values for the "low_battery", "locked" and "window_open" sensors
> add payload type for thermostat auto config

- workers/base.py
The recent merged PR #79 uses a MAC as a node id for home assistant auto discovery. However: As it turns out the `:` character is not [allowed](https://github.com/home-assistant/home-assistant/blob/0.96.3/homeassistant/components/mqtt/discovery.py#L18). This fixes the format by using `-` instead of `:`.
> Make node id compatible with HA discovery

- workers/thermostat.py
Parsing of commands in `workers/thermostat.py` fail when the topic prefix contains slashes. This change subtracts the known topic prefix before extracting elements.
> Support multiple slashes within topic prefix

- config.yaml.example
- workers/thermostat.py
The discovery feature creates a [MQTT HVAC](https://www.home-assistant.io/components/climate.mqtt/) device in HASS. As we know, the eQ-3 thermostat doesn't provide any temperature readings on its own. However, one can set a custom `current_temperature_topic` on the MQTT HVAC device and get the temperature from somewhere else, like a separate temperature sensor.
As the device configuration in HASS is originating from bt-mqtt-gateway, we have to set these options within bt-mqtt-gateway itself. This PR adds support for this use case.
> HASS autodiscovery: Support current temperature topic and template

- workers/mithermometer.py
When having more than one device, if one was timing out, no device was
being updated. This was caused because the exception was not handled and the full worker was cancelled before sending the updates.
This PR fixes this, handling the exception properly, logging it but continuing by updating the devices that didn't time out.
> Handle TimeoutError exception properly in mithermometer

- gateway.py
- mqtt.py
- workers/base.py
- workers/blescanmulti.py
- workers/ibbq.py
- workers/miflora.py
- workers/mithermometer.py
- workers/thermostat.py
- workers_manager.py
Setting the global topic prefix in ``mqtt`` -> ``topic_prefix`` is a good option for separating functionality of multiple gateways, and avoiding issues like #53.
The autodiscovery information sent to Home Assistant is however incorrect if the option is set. As a consequence, the devices appear but status information is not visible. There are two causes for the problem:
1. If the global prefix is set, the configuration messages' topics are prefixed with it. HASS is not going to receive them.
2. The worker method ``format_topic`` is not aware of the global prefix, so it does not include it when formatting the config message for HASS. As a result, HASS subscribes to the wrong topics and sends messages that no client is subscribed to.
This PR addresses both aforementioned issues.
Please …
> Support Home Assistant autodiscovery with global prefix

- .gitignore
- README.md
- bt-mqtt-gateway.service
- service.sh
In order to avoid Python package conflicts on a system level (or just keeping the global installation clean) it is considered good practice to create virtual environments. This requires the additional Python package ``virtualenv`` to be installed globally, but removes the requirement to use ``sudo``.
This PR includes changes in installation instructions, and an additional script for running bt-mqtt-gateway as a systemd service. There is a new script ``service.sh`` which changes the Python path variables (which is essentially what Python virtualenv does). It still works if Python virtual environments are not used.
Modifying ``start.sh`` did not make sense for this purpose, since that script is used for starting a Docker container where virtual environments are redundant.
> Install packages using a virtual environment

- workers/thermostat.py
After submitting a command to a `ThermostatWorker` (e.g. change of temperature), a state update is requested from the underlying `Thermostat` instance before re-reading monitored attributes and reporting back via MQTT. I have observed however (using the `python-eq3bt` CLI in debug mode) that in the response of the initial command, the thermostat already returns a full status message which is immediately processed. As a consequence, the `Thermostat` instance is already up-to-date, making another `update` call redundant.
This PR removes the additional Bluetooth request, and simply re-uses the response already received directly after an attribute update. This made it necessary to separate the `Thermostat.update()` call from the rest of `update_device_state`. In return this speeds up the …
> Skip redundant Thermostat state update

- start.sh
The issue was essentially this, I'm running a raspberry pi:
```
$ docker-compose logs -f --tail=1000 bt2mqtt
Attaching to bt2mqtt
bt2mqtt          | standard_init_linux.go:211: exec user process caused "exec format error"
```
And then I looked closer and found this: https://www.lewuathe.com/exec-format-error-in-docker-container.html
> Address "exec format error" in docker

- Dockerfile.arm32v7
- hooks/post_push
- hooks/pre_build
- multi-arch-manifest.yaml
This adds docker setup for arm32v7 architecture (with support of more potentially).
Partially implements #78.
A following build config change needs to be made on docker hub to make this work:
"default" must be tagged amd64 and there's separate build step for arm32v7.
I used this guide mostly: https://github.com/ckulka/docker-multi-arch-example
- I verified this setup in my own docker repo: https://hub.docker.com/r/krasnoukhov/bt-mqtt-gateway/builds
- After builds completed, I was able to use `image: krasnoukhov/bt-mqtt-gateway` in my docker-compose on raspberry pi with no additional config, thanks to manifest push
- I could not find a way to somehow reuse existing Dockerfile so I copied it (and adjusted to pull qemu in), maybe @hobbypunk90 has an idea on how to organize this better?
- I …
> arm32v7 docker build setup

- const.py
- exceptions.py
- gateway.py
- workers/miflora.py
- workers/mithermometer.py
- workers/switchbot.py
- workers/thermostat.py
- workers/toothbrush.py
- workers/toothbrush_homeassistant.py
- workers_manager.py
When one device, in worker, timeouts, none of the messages from devices that responded, are being sent via mqtt. It should be fixed now.
Fixes #65, #95
> Return workers response asap

- workers_manager.py
pip >= 19.3.1 changed its internal API: https://github.com/pypa/pip/commit/09fd200c599de4fadf2ff814a1bef855bc6d77e8#diff-cf86c603e352099be697d1bd01c2d191
This resulted in the following error:
```Traceback (most recent call last):
File "gateway.py", line 67, in <module>
manager.register_workers(global_topic_prefix).start(mqtt)
File "/bt-mqtt-gateway/workers_manager.py", line 82, in register_workers
self._pip_install_helper(module_obj.REQUIREMENTS)
File "/bt-mqtt-gateway/workers_manager.py", line 182, in _pip_install_helper
pip_main(["install", "-q", package])
TypeError: 'module' object is not callable
```
This PR takes that API change into account.
> Compatibility for internal API change of pip >= 19.3.1

- workers/miflora.py
Commit b379580 changed the miflora version to 0.0.5, but this version doesn't exist. This pull request fixes it by changing it to 0.5, which seems to have been the intention. I confirmed that this works with my Xiaomi Mi Flora sensor.
> Fix wrong miflora version in commit b379580

- README.md
- config.yaml.example
- workers/lywsd02.py
This includes clocks and dedicated temperature/humidity sensors family known as LYWSD02.
I got my hand on one of those literally for few hours and managed to make it work with bt-mqtt-gateway pretty easily. There's much more to implement, especially support for setting time, units (C/F) and maybe even history. That said - with this code it's possible to read it but it needs to be configured separately.
I structured the code similarty to IBBQ one, as it's pretty similar use case when we connect with bluepy.
```
2019-11-10 17:48:05,571 DEBUG bt-mqtt-gw.workers.lywsd02 lywsd02.py:59:connected - xx:xx:xx:xx:xx:xx connected
2019-11-10 17:48:25,924 DEBUG bt-mqtt-gw.workers.lywsd02 lywsd02.py:76:readAll - Read 21.820000, 60, 52
2019-11-10 17:48:25,931 DEBUG bt-mqtt-gw.workers_manager …
```
> Add support for second generation of Xiaomi climate sensors

- workers/ruuvitag.py
This adds a low battery binary sensor to the RuuviTag worker. I also added a table in the comments with an overview of the available attributes in each Data Format of the sensor.
> Add low battery sensor to RuuviTag worker

- workers/ruuvitag.py
The RuuviTag worker configured some device classes that don't exist, which resulted in Home Assistant showing errors. This pull request fixes this by setting these device classes to `none`.
> Change invalid device classes to none

- workers/miflora.py
This change forces the inclusion of the transitive dependency `btlewrap` in version 0.0.9 to fix #108.  This should be reverted to just `miflora` once miflora version > 0.6 is available on [pypi](https://pypi.org/project/miflora/).
> Bump miflora to include btlewrap 0.0.9

- workers/mithermometer.py
Bump mithermometer, as it also uses btlewrap.
Fixes https://github.com/zewelor/bt-mqtt-gateway/issues/108
> Bump mithermoter version

- workers/smartgadget.py
This PR updates the SmartGadget worker to return the status as a generator. A similar change has already been implemented to most other workers (PR #96) for facilitating partial status updates (e.g. in case of timeouts).
> Migrated SmartGadget state update to generator function

- workers/thermostat.py
Thanks to @krasnoukhov for implementing #121 and the modification of the MQTT component of Home Assistant. I had some issues using this however:
* Whenever setting the state to **Heat**, the thermostat activated **Boost** mode. Before #121, the thermostat changed to **Manual**, which is also the behavior of the [built-in **eq3btsmart** component](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/eq3btsmart/climate.py). The latter seems more predictable and appropriate to me. For setting boost mode, there is still the possibility to use the preset (hold mode).
* In my setup, neither of the presets **Eco** and **Comfort** worked as expected. They were directly linked to the thermostat state, but are actually separate concepts on the device as well. For …
> More consistent state and hold mapping on EQ3

- config.py
- gateway.py
- workers/blescanmulti.py
- workers/ibbq.py
- workers/lywsd02.py
- workers/toothbrush.py
- workers/toothbrush_homeassistant.py
- workers_manager.py
- workers_requirements.py
Added switch to list all requirements, from all workers, or from configured only. Also fixes for few workers, to import libs inside method calls.
> Add command to print all requirements, or configured only

- workers/thermostat.py
Device names are retrieved by the configuration file. If an MQTT command is
handled but contains an unknown device name, which is not in the configuration
file a KeyError was thrown and the application was terminated. This commit
checks if the device name is known, if not it logs an error message but will not
fail.
Fixes KeyError exception #53
> fix unknown device name in command message

- workers/miscale.py
This update fixes incorrect body metric calculations if the scale is set to lbs by checking the unit and converting to kg if necessary.
> Fix calculations in miscale.py for scales set to lbs unit

- config.yaml.example
- const.py
- workers/miflora.py
- workers/mithermometer.py
This PR adds an option to override the default device timeout in configuration file for mithermomether device.
> Create a possibility to override default device timeout

- config.yaml.example
- workers/lywsd03mmc_homeassistant.py
Adds a worker named lywsd03mmc_homeassistant. It's loosely based on the existing MiFlora worker, but also the original lywsd03mmc worker. It also integrates the connection enhancements in PR #173. 
It creates all of the sensor entries for home assistant, as well as a binary sensor for the battery status.
- [ x] New feature (non-breaking change which adds functionality)
> Adds lywsd03mmc_homeassistant worker.

- gateway.py
- workers_manager.py
- workers_requirements.py
1. Removes installation of configured requirements via pips [deprecated API](https://pip.pypa.io/en/latest/user_guide/#using-pip-from-your-program) at runtime all together.
2. Verifies configured requirements on startup and prints a nice error message in case any requirements aren't met.
This might break existing setups, because the implementation now exits unconditionally when requirements are not met. Are there other conditions, where this could break something? How about Docker?
Fixes #184
Example for a fully fledged configuration:
```
13:00:16 Starting
13:00:16 Error: unsatisfied requirements:
13:00:16   The 'miflora' distribution was not found and is required by the application
13:00:16   The 'python-eq3bt==0.1.11' distribution was not found and is required by the application …
```
> Replace requirements installation at runtime with requirement verification

- config.yaml.example
- workers/am43.py
Adds support for AM43 based blinds #209.
This uses the [python-zemismart-roller-shade](https://github.com/GylleTanken/python-zemismart-roller-shade) library for working with the device. 
This publishes a number of messages under the root topic `<topic prefix>/<device name>`. This root topic gets a state message published like this:
```
{"currentPosition": 100, "targetPosition": 91, "battery": 41, "positionState": "STOPPED"}
```
Messages containing the raw value for each of these fields are published under the topics `<topic prefix>/<device name>/<field  name>`.
While this uses the `update_interval` configuration to poll on a schedule, an on demand status update can be triggered by sending an empty message to `<topic prefix>/<device name>/status/get`. The `status` part can be any string, I …
> Add support for am43 blind devices

- .github/workflows/docker.yml
After this change github-actions would start building ARMv6 images in addition to existing ones.
I'm building my own cluster of RPi0, to use in home automation and the easiest way to deploy everything is to use Docker. Yeah, I know that it's crazy — to use Docker on rpi0, but anyway.
> Add ARMv6 docker build

- config.yaml.example
- workers/am43.py
In this PR, I continue to improve the AM43 worker: I made a few mistakes in the state detection logic in the last one, especially when blinds have moved since the previous update.
Also, in the previous PR, I added some magic to automatically reduce desired update interval to 3 seconds when some changes were detected — to handle the complete open/close procedure quickly: now I moved this hardcoded 3 seconds to a configuration variable, documenting both `default_update_interval` and the new `rapid_update_interval` on the way.
In addition, I've switched the worker to use a patched Zemismart driver, which helps to detect whether a command was successful.
Plus, now you can select a desired device class for the blinds in HASS (previously, it was hardcoded) :)
Please delete options that are not …
> Am43 improvements pt2

- workers/lywsd03mmc_homeassistant.py
In some cases (e.g. device is completely out of battery), the whole execution will fail with a TypeError,  preventing live devices from updating as well.
Before the change, bt-mqtt-gateway would completely crash with this error:
```
bt-mqtt-gateway_1  | 14:46:36 Fatal error while executing worker command: TypeError
bt-mqtt-gateway_1  | Traceback (most recent call last):
bt-mqtt-gateway_1  |   File "./gateway.py", line 108, in <module>
bt-mqtt-gateway_1  |     raise e
bt-mqtt-gateway_1  |   File "./gateway.py", line 90, in <module>
bt-mqtt-gateway_1  |     mqtt.publish(_WORKERS_QUEUE.get(timeout=10).execute())
bt-mqtt-gateway_1  |   File "/application/workers_manager.py", line 45, in execute
bt-mqtt-gateway_1  |     for message in self._callback(*self._args):
bt-mqtt-gateway_1  |   File …
```
> avoiding data errors (e.g. device out of reach/battery)

- config.yaml.example
- workers/miflora.py
Currently MifloraWorker is hardcoded to the 'hci0' adapter.
Since hosts might have multiple adapters, allow selecting a
different one via the config.yaml.
Example:
miflora:
update_interval: 300
args:
adapter: hci3
devices:
myplant: AA:BB:CC:DD:EE:FF
Signed-off-by: Philippe Mathieu-Daudé <f4bug@amsat.org>
> miflora: Allow using different host adapter

- workers/switchbot.py
When the switchbot fails to connect, the worker doesn't retry the action. With this change this is solved used the base worker retry function.
Also the worker has been modified to store the current state of the switch son now you can see the correct state in the MQTT status and now if the status has changed or not
Fixes #231 
> Added retry to switchbot worker

- workers/thermostat.py
[Home Assistant](https://www.home-assistant.io/) picks up and autoconfigures perfectly the EQ3 thermostats exposed by this project.
A small issue is that the exposed valve sensor, as it is, is not recorded for long-term statistics as it lacks a couple of specifications. This makes it impossible for example to have a panel showing the heating usage per room throughout the day/week/month/year.
This PR adds `device_class` and `state_class` to the autodiscovery configuration for HA so that the correct icon is shown and statistics are possible.
I tested this works in my own HA instance by [building my own forked image](https://hub.docker.com/repository/docker/nonninz/bt-mqtt-gateway) and swapping it in `docker-compose.yaml`. The valves were immediately picked up with the correct type and …
> Add `device_class` and `state_class` to EQ3 Valve Sensor

- config.yaml.example
- workers/thermostat.py
Bluetooth interface selection for thermostat communication was added to python-eq3bt in version 0.1.12. This change allows choosing the Bluetooth interface via the configuration file.
> Bump eq3bt and allow interface selection for thermostat

- workers/miflora.py
miflora > 0.6 is available on pypi, so we can revert the dependency on a specific (old) commit of the miflora library.
This is actually just following a comment in the code which mentions that this can be done. The newer version seems to work fine here.
> revert specific commit miflora version dependency
