workers_manager.py
=> add a switch for pip versions < 10.0

mqtt.py, workers/thermostat.py
=> Fix global topic prefix handling

mqtt.py
Use a single mqtt connection for publish and subscribe operations instead of separate one-shot connections for each update. Fixes #34.
=> Use a single mqtt connection

.gitignore, .vscode/settings.json, README.md, config.yaml.example, workers/blescanmulti.py
BLE devices scanner worker. It can be used to check proximity of beacons, smartwatch, etc...
=> New worker: ble devices scanner

workers_manager.py
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> Test force utc timezone

config.py
Load config from relative location.
https://github.com/zewelor/bt-mqtt-gateway/pull/50#issuecomment-463304618
=> Improve config loading

README.md, config.yaml.example, workers/toothbrush.py
Added a worker that scans Oral-B connected BLE toothbrushes, based on [this script](https://github.com/rfaelens/domotica/blob/master/mqtt-toothbrush.py) found here https://community.home-assistant.io/t/oral-b-bluetooth-connected-toothbrush/.
=> Add worker for Oral-B connected toothbrush

README.md
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> Add example worker to readme

README.md, config.yaml.example, workers/switchbot.py
Added support for Switchbot. The worker code was modified from thermostat.py as it has on_command example. [This](https://www.switch-bot.com/) is a switch that uses BLE to trigger a rocker switch or button on/off. Dependencies that are required for this change: binascii.
=> Added support for Switchbot

mqtt.py, workers/base.py, workers/miflora.py, workers/mithermometer.py, workers/thermostat.py
Hey,
after starting using @hobbypunk90 auto discovery integration (Thank you!) I noticed a bug: Using a device topic prefix with a slash leads to that slash being preserved when [forming the topic](https://github.com/zewelor/bt-mqtt-gateway/blob/8fbf3540bd8058ad9054fc4a3d4552420865335e/workers/mithermometer.py#L34) where the config is being send to.
So a topic prefix of `foo/bar/baz` leads to something like: `homeassistant/sensor/foo/bar/baz_thermometer_bedroom_temperature/config` and is thus violating the [discovery protocol](https://www.home-assistant.io/docs/mqtt/discovery/).
While fixing the bug I also also started to restructure a few bits here and there (inspired by zigbee2mqtt):
* Group multiple sensors of a device under a common …
=> Improve home assistant auto discovery

config.yaml.example, mqtt.py
Add TLS support for MQTT.  Not completely sure this is the correct way to implement this for MQTT, but I followed other examples I found that worked. Comments welcomed, what can I do better!
Fixes # N/A
- New feature (non-breaking change which adds functionality)
=> Add TLS Support for MQTT

README.md, config.yaml.example, workers/smartgadget.py
This PR adds a worker for reading temperature, humidity, and battery level from a Sensirion SHT31 Smart Gadget Development Kit. This is done through the additional library `python-smartgadget`.
=> Support for SHT31 Smart Gadget by Sensirion

const.py, exceptions.py, gateway.py, logger.py, mqtt.py, utils.py, workers/base.py, workers/blescanmulti.py, workers/ibbq.py, workers/linakdesk.py, workers/miflora.py, workers/miscale.py, workers/mithermometer.py, workers/mysensors.py, workers/smartgadget.py, workers/switchbot.py, workers/thermostat.py, workers/toothbrush.py, workers/toothbrush_homeassistant.py, workers_manager.py, workers_queue.py
=> Black reformat

workers/blescanmulti.py
Add some logging messages.
Other workers send several logging messages, this worker doesn't, so I add two messages about adding device and updating status. maybe someone can add other messages with more details.
=> Update blescanmulti.py with some logging messages

Dockerfile.arm64v8, multi-arch-manifest.yaml
Add support for arm64 systems.
=> Aarch64 /Arm64v8 support

README.md, config.yaml.example, workers/ruuvitag.py
Adds support for the RuuviTag sensor, which measures temperature, humidity, pressure and acceleration.
=> Add support for RuuviTag sensor

Dockerfile, Dockerfile.arm32v7, Dockerfile.arm64v8, workers/ruuvitag.py
This makes the ruuvitag worker usable by fixing two issues:
- Removes a superfluous method that slowed down the update interval.
- Fixes #115 so the Docker containers work with the ruuvitag worker.
=> Fixes for ruuvitag worker

workers/smartgadget.py, workers/switchbot.py
I don't think this method is used anymore, lets remove it to confirm.
=> Remove unneeded device_for method

workers/thermostat.py
Since HA 0.96 the thermostat integration is really broken since HA introduced strict state/mode mapping. Here's a [commit](https://github.com/zewelor/bt-mqtt-gateway/commit/d1f2a1209262d08597da71c0426024369057ab14) to remove non-supported modes. This PR brings modes back by using "hold modes" which act like presets in the UI.
After this patch has been merged in HA these changes should work as expected: https://github.com/home-assistant/home-assistant/pull/28988
- New states: **Heat**, **Auto**, **Off** (breaking!)
- New presets for Heat: **Boost**, **Comfort** (manual), **Eco**, and the default **None** which sets state to **Off**
- Away mode is removed in favor of **Eco** preset (breaking!)
- **On** mode is not supported since there's no HA mapping (suggestions welcome, maybe map to …
=> Thermostat state and mode mapping

workers/miflora.py
Bump miflora to latest version
=> Bump miflora

mqtt.py, workers/miscale.py
Small cleanups ( black reformat ) and mqtt auto dict dump.
=> Black reformat and small improvements

workers/thermostat.py
Add json attributes for thermostat. Also fix none preset
=> Add thermostat json attributes topic

workers/blescanmulti.py
Add exception handling for ble multiscan
Fixes https://github.com/zewelor/bt-mqtt-gateway/issues/140
=> Add exception handling for ble multiscan

.dockerignore, Dockerfile, Dockerfile.arm32v7, Dockerfile.arm64v8, README.md, start.sh
Cleanups / improvements to docker setup. It now builds faster, uses better layer caching. Also its simpler. 
It also installs all requirements.
It uses volume /config.yaml for config, example run in README
Fixes https://github.com/zewelor/bt-mqtt-gateway/issues/143
=> Improve docker setup

config.yaml.example, workers/lywsd03mmc.py
Added Support for Xiaomi LYWSD03MMC based on source code of lywsd02.py
- [x ] New feature (non-breaking change which adds functionality)
=> [~FEATURE] Add Xiaomi LYWSD03MMC Support

workers/lywsd02.py, workers/lywsd03mmc.py
Fix multiple device update for xiaomi thermometers
Fixes https://github.com/zewelor/bt-mqtt-gateway/issues/169
=> Fix multidevice update

workers/base.py, workers/lywsd02.py, workers/lywsd03mmc.py
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> Fix lywsd multi device update

README.md
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> fix virtualenv installation on debian 9

workers/miscale.py
Fixes issue with too high impedance value. Impedance value 65533 appears if someone is not barefoot during measurement. PR contains also a tiny refactor.
Fixes #148
=> Out of range impedance value

config.yaml.example, workers/lywsd03mmc.py
The Xiaomi LYWSD03MMC can be flashed over Bluetooth, for more information: https://github.com/atc1441/ATC_MiThermometer
With the custom firmware the temperature, humidity and battery can be read passive. This change adds support for passive readout.
=> add passive read for lywsd03mmc with custom firmware

workers/lywsd03mmc.py
fix for missing config item check
=> Add check for scan_timeout in config

workers/lywsd03mmc_homeassistant.py
* reducing code duplication by re-using the lywsd03mmc class within the
homeassistant class
Fixes #215
=> fixes #215 refactor lywsd03mmc_homeassistant to use lywsd03mmc

workers/blescanmulti.py
Pass arguments via args and kwargs to BaseWorker.
Fix for https://github.com/zewelor/bt-mqtt-gateway/commit/5fd21c45f7a6a8be6969a80411238d6fe6ab9824#commitcomment-47475758
=> Pass arguments via args and kwargs to BaseWorker

mqtt.py, workers/am43.py
* Add Home-Assistant autodiscovery
* Add open/stop/close commands
* Reduce update interval when blinds are moving after a command, and revert it back to the default when stopped. `default_update_interval` has to be added to `args` in order to get this working.
Everybody who uses AM43 now and reads `positionState` topic would need to update their automation: I'm setting new values there.
=> Improve AM43 worker

workers/lywsd03mmc.py
Fixed missing/wrong declared Variable
Fixes #210
- [x ] Bug fix (non-breaking change which fixes an issue)
=> [Fixed #210] normalize variable

mqtt.py, workers/am43.py
I built this PR on top of #233, to reduce conflicts during the merge. I decided to make it a separate PR because the timer-related changes are extremely ugly implemented. At least in terms of HomeAssistant autodiscovery.
I'm open to ideas, how to make it better :)
=> Am43 improvements pt3

config.yaml.example, mqtt.py, workers/lightstring.py
* Add Mosquitto client certificate authentication support
* Add support for Lightstring devices controlled by the Android App "Lights App": https://play.google.com/store/apps/details?id=com.scinan.novolink.lightstring
=> Add Mosquitto client certificate auth + Add support for a Lightstring device

workers/thermostat.py
This addresses #261 were the separate hold and away topics got deprecated and merged into a preset topic. The technical behavior should be the same as before. Asking for a review from @merll, @krasnoukhov or @zewelor.
Pointers:
- `HOLD` mode is basically now a `PRESET` mode
- `AWAY` is moved to the preset category
- Renamed `STATE` to `MODE` and `HOLD` to `PRESET` to match the HA terminology
=> Replace deprecated hold and away modes with presets
